### ISSUE TITLE
Xcode not reflecting filesystem: Missing directories post-repo cloning

### ISSUE THREAD

**Issue by Diana-Paez** [Jaime-A-Perez/To-Do-List-Apple-Ecosystem#18] opened 2023-12-29 21:35 UTC
---
name: Bug report
about: Xcode project not reflecting filesystem structure
title: 'Xcode does not show directories despite presence in filesystem'
labels: 'bug, xcode, filesystem'
assignees: 'Jaime-A-Perez'

---

**Describe the bug**
After cloning the repository and switching to the `develop` branch, certain directories (`AuthModels` and `AuthViewModels`) that are present in the filesystem are not being displayed in the Xcode project navigator.

**To Reproduce**
1. Clone the repo `git clone https://github.com/Jaime-A-Perez/To-Do-List-Apple-Ecosystem`
2. Switch to the develop branch `git checkout develop`
3. Open the project in Xcode `open ToDoListAppPro.xcodeproj`
4. Observe that `AuthModels` and `AuthViewModels` directories are not displayed in the project navigator

**Expected behavior**
All directories and files that are present in the filesystem after cloning the repository should be visible and properly referenced in Xcode's project navigator.

**Desktop (please complete the following information):**
 - OS: macOS
 - Xcode version: 15.1

**Additional context**
The missing directories were added manually to the project as folder references, and they appear as blue folders in Xcode. Running `git status` reveals changes in the `project.pbxproj`, which seem to be related to the manual addition of these directories.

**Comment by Jaime-A-Perez** [comment] 2024-01-02 21:21
Hello Diana,

Thank you for bringing this issue to our attention! I have reviewed the problem you described and can confirm that the AuthModels and AuthViewModels directories are not showing up in Xcode's project navigator after following the steps you provided. This behavior is indeed unexpected, and I appreciate you pointing it out.

It appears that the issue is related to how these folders were added to the Xcode project. Manually adding directories as folder references can cause such discrepancies, especially if the changes are not properly reflected in the project.pbxproj file.

Thank you again for your contribution to improving the quality of the project.

**Comment by Jaime-A-Perez** [comment] 2024-01-02 21:50
With the successful merge of Pull Request #19 , which addressed the missing folder references in the Xcode project, I am closing Issue #18. All directories should now be visible in the project navigator as expected.

Thank you all for your contributions and support in resolving this issue.

**Closed as completed by Jaime-A-Perez** 2024-01-02 21:50 UTC
Labels: bug
